// Scores include ancestry and the level-4 +2 increase named on each sheet.
export const modifier = score => Math.floor((score - 10) / 2)
export const signed = value => value >= 0 ? `+${value}` : `${value}`
const t = (en, th) => ({ en, th })

export const characters = [
  {
    id: 'aster', name: 'Aster Vane', ancestry: t('Human', 'มนุษย์'), klass: 'Fighter', subclass: 'Champion',
    role: t('No-Coin courier · custom courier background', 'คนส่งของ No-Coin · ภูมิหลังคนส่งของ'),
    level: 5, hitDie: 10, hp: 44, ac: 18, speed: 30, scores: [18, 14, 14, 10, 12, 8], asi: 'STR',
    saves: ['STR', 'CON'], skills: { Athletics: 1, Intimidation: 1, Perception: 1, Survival: 1 },
    attacks: [{ name: 'Longsword', ability: 'STR', dice: '1d8', type: 'slashing', extra: 2, range: '5 ft' }, { name: 'Light crossbow', ability: 'DEX', dice: '1d8', type: 'piercing', range: '80/320 ft' }],
    features: t('Dueling adds +2 damage with the one-handed longsword (included). Attack action: two sword attacks; crossbow Loading permits only one bolt per action. Second Wind: bonus action, regain 1d10+5 HP, once per short/long rest. Action Surge: one additional action, once per short/long rest. Weapon attacks critically hit on 19–20. Human ability increases are included.', 'Dueling เพิ่มความเสียหาย Longsword มือเดียว +2 (รวมแล้ว) ใช้ Attack โจมตีดาบได้สองครั้ง แต่ Loading จำกัดหน้าไม้หนึ่งนัดต่อแอ็กชัน Second Wind ใช้โบนัสแอ็กชัน ฟื้น 1d10+5 HP หนึ่งครั้งต่อการพักสั้นหรือยาว Action Surge เพิ่มหนึ่งแอ็กชันต่อการพักสั้นหรือยาว อาวุธติดคริติคอลเมื่อทอยได้ 19–20 รวมค่าความสามารถจากมนุษย์แล้ว'),
    equipment: t('Chain mail, shield, longsword, light crossbow, 20 bolts, explorer’s pack, gold comm-stone. Put the shield away (one action) before using the two-handed crossbow. Tools: land vehicles, cartographer’s tools. Languages: Common, Infernal. Background: know courier routes and obtain an introduction to a local dispatcher; no automatic checkpoint access.', 'Chain mail, โล่, Longsword, Light crossbow, ลูกดอก 20 ดอก, Explorer’s pack และ Gold comm-stone เก็บโล่ด้วยหนึ่งแอ็กชันก่อนใช้หน้าไม้สองมือ เครื่องมือ: พาหนะทางบกและเครื่องมือทำแผนที่ ภาษา: Common, Infernal ภูมิหลังช่วยให้รู้เส้นทางและขอพบผู้จ่ายงานได้ แต่ไม่ให้สิทธิผ่านด่านอัตโนมัติ'),
    story: t('Ideal: freedom. Flaw: never leaves a debt unpaid. Kael saved your sister. Nyx entrusted you with her spare key; you trust her because she returned your wages untouched. Protect the clinic’s patients before chasing a payout.', 'อุดมคติคืออิสรภาพ จุดอ่อนคือไม่ยอมค้างหนี้ Kael เคยช่วยน้องสาวคุณ Nyx ฝากกุญแจสำรองไว้กับคุณ คุณเชื่อใจเธอเพราะเธอเคยคืนค่าจ้างครบทุกเหรียญ ปกป้องผู้ป่วยก่อนคิดถึงเงินรางวัล'),
    turn: t('Stand beside an ally, attack twice with the sword, then use Second Wind if hurt. Reserve Action Surge for an urgent rescue or dangerous enemy.', 'ยืนข้างเพื่อน โจมตีดาบสองครั้ง ใช้ Second Wind เมื่อบาดเจ็บ เก็บ Action Surge ไว้ช่วยคนหรือรับมือศัตรูอันตราย'),
  },
  {
    id: 'nyx', name: 'Nyx Arclight', ancestry: t('High elf', 'เอลฟ์ชั้นสูง'), klass: 'Wizard', subclass: 'School of Divination',
    role: t('Soulhacker · Ethereal Soulhacker background', 'Soulhacker · ภูมิหลังแฮกเกอร์แห่ง Ethereal'),
    level: 5, hitDie: 6, hp: 32, ac: 12, speed: 30, scores: [8, 14, 14, 18, 12, 10], asi: 'INT',
    saves: ['INT', 'WIS'], skills: { Arcana: 1, History: 1, Investigation: 1, Perception: 1, 'Sleight of Hand': 1 },
    attacks: [{ name: 'Dagger', ability: 'DEX', dice: '1d4', type: 'piercing', range: '5 ft / 20/60 ft' }, { name: 'Fire Bolt', ability: 'INT', dice: '2d10', type: 'fire', spell: true, range: '120 ft' }],
    casting: { ability: 'INT', slots: [4, 3, 2], cantrips: ['Fire Bolt', 'Mage Hand', 'Minor Illusion', 'Ray of Frost', 'Prestidigitation (ancestry)'], prepared: ['Mage Armor', 'Shield', 'Magic Missile', 'Detect Magic', 'Misty Step', 'Invisibility', 'Web', 'Counterspell', 'Fireball'], book: ['Mage Armor', 'Shield', 'Magic Missile', 'Detect Magic', 'Identify', 'Find Familiar', 'Comprehend Languages', 'Feather Fall', 'Misty Step', 'Invisibility', 'Web', 'Mirror Image', 'Counterspell', 'Fireball'] },
    features: t('Portent: after each long rest record two d20 rolls; replace a visible creature’s attack, save or ability roll before it is rolled, at most once per turn. Arcane Recovery: once per day after a short rest regain slots totaling up to 3 levels. Rituals in your spellbook need not be prepared; add 10 minutes. Darkvision 60 ft; advantage against charm; magical sleep immunity; 4-hour trance (follow your table’s 2014 rest ruling). Longsword, shortsword, shortbow and longbow proficiency. Mage Armor makes AC 15 for 8 hours and spends a slot; base AC above assumes no spell.', 'Portent: หลังพักยาวทอย d20 สองลูกแล้วจดไว้ ใช้แทนการโจมตี เซฟ หรือเช็กของผู้ที่มองเห็นก่อนทอยจริงได้ไม่เกินเทิร์นละครั้ง Arcane Recovery: วันละครั้งหลังพักสั้น ฟื้นช่องเวทรวมไม่เกินระดับ 3 ร่ายพิธีกรรมจากสมุดได้โดยไม่ต้องเตรียม เพิ่มเวลา 10 นาที มองในความมืด 60 ฟุต ได้เปรียบเซฟต้าน charm ไม่หลับด้วยเวท เข้าภวังค์ 4 ชั่วโมง โดยใช้ข้อตกลงการพักฉบับ 2014 ของโต๊ะ ชำนาญ Longsword, Shortsword, Shortbow, Longbow เมื่อใช้ช่องเวทร่าย Mage Armor จะมี AC 15 นาน 8 ชั่วโมง ค่า AC หลักยังไม่รวมเวท'),
    equipment: t('Dagger, spellbook, arcane focus/projector, component pouch, scholar’s pack, forgery kit. Tools: projector (use thieves’ tools proficiency at arcane consoles), forgery kit. Languages: Common, Elvish, Draconic. No familiar summoned at start; Find Familiar requires 10 gp consumed materials. Identify needs a 100 gp pearl, not supplied. See the player primer for the Backdoor background feature.', 'Dagger, สมุดเวท, โฟกัสหรือ Projector, Component pouch, Scholar’s pack และ Forgery kit เครื่องมือ: Projector ใช้ความชำนาญ Thieves’ Tools ที่แผงอาคม และ Forgery kit ภาษา: Common, Elvish, Draconic เริ่มโดยยังไม่มี Familiar ต้องใช้วัตถุดิบ 10 gp ที่ถูกใช้หมด ส่วน Identify ต้องมีไข่มุก 100 gp ซึ่งยังไม่ได้รับ อ่านความสามารถ Backdoor ในคู่มือผู้เล่น'),
    story: t('Ideal: truth should be free. Flaw: trusts systems more than people. The kitchen taught you to cook when your stipend vanished. Aster protected your key; you trust Sable because she warned you about a corporate audit. Your faction complication is a revoked archive license.', 'อุดมคติคือความจริงต้องเข้าถึงได้ จุดอ่อนคือเชื่อระบบมากกว่าคน โรงครัวสอนคุณทำอาหารเมื่อเงินเลี้ยงชีพหายไป Aster ปกป้องกุญแจของคุณ คุณเชื่อ Sable เพราะเธอเตือนเรื่องการตรวจองค์กร ปัญหากับฝ่ายอำนาจคือใบอนุญาตคลังที่ถูกเพิกถอน'),
    turn: t('Use Fire Bolt when conserving slots. Web restrains a group but needs concentration; keep allies out of Fireball. Shield uses your reaction. You can concentrate on only one spell.', 'ใช้ Fire Bolt เพื่อประหยัดช่องเวท Web ช่วยตรึงศัตรูแต่ต้องใช้สมาธิ ระวังเพื่อนในพื้นที่ Fireball ส่วน Shield ใช้รีแอ็กชัน รักษาสมาธิได้ครั้งละหนึ่งเวท'),
  },
  {
    id: 'sable', name: 'Sable Thorn', ancestry: t('Tiefling', 'ทิฟลิง'), klass: 'Warlock', subclass: 'The Fiend · Pact of the Chain',
    role: t('Corporate defector · Corporate Drone background', 'ผู้แปรพักตร์ · ภูมิหลังอดีตพนักงานองค์กร'),
    level: 5, hitDie: 8, hp: 38, ac: 14, speed: 30, scores: [8, 14, 14, 10, 10, 18], asi: 'CHA', pledge: 10, soulcoin: 20,
    saves: ['WIS', 'CHA'], skills: { Deception: 1, Intimidation: 1, Investigation: 1, Persuasion: 1 },
    attacks: [{ name: 'Eldritch Blast', ability: 'CHA', dice: '1d10', type: 'force', spell: true, addAbility: true, range: '120 ft × 2 beams' }, { name: 'Dagger', ability: 'DEX', dice: '1d4', type: 'piercing', range: '5 ft / 20/60 ft' }],
    casting: { ability: 'CHA', slots: [0, 0, 2], pact: true, cantrips: ['Eldritch Blast', 'Mage Hand', 'Minor Illusion', 'Thaumaturgy (ancestry)'], known: ['Armor of Agathys', 'Hex', 'Command', 'Invisibility', 'Counterspell', 'Fireball'], innate: ['Hellish Rebuke (2nd level, once/long rest)', 'Darkness (once/long rest)'] },
    features: t('Invocations: Agonizing Blast (+CHA to each beam, included), Devil’s Sight (see normally in magical/nonmagical darkness to 120 ft), Mask of Many Faces (Disguise Self at will). Dark One’s Blessing: reducing a hostile creature to 0 HP grants 9 temporary HP; temporary HP never stack. Fire resistance; darkvision 60 ft. Pact of the Chain grants Find Familiar as a ritual. Existing familiar is an ordinary owl named Cinder: AC 11, HP 1, walk 5/fly 60 ft, STR 3 DEX 13 CON 8 INT 2 WIS 12 CHA 7, Perception +3, Stealth +3, darkvision 120 ft, passive Perception 13, advantage on hearing/sight Perception; Flyby avoids opportunity attacks when flying out of reach. It understands your languages, cannot speak, acts on its own initiative and can Help. You may use an action to see/hear through it until your next turn within 100 ft; your own senses are unavailable then. It normally cannot attack; you may forgo one Attack-action attack to let it use its reaction for talons (+3, 1 slashing). Replacing it consumes 10 gp materials.', 'Invocations: Agonizing Blast เพิ่ม CHA ต่อแต่ละลำแสง (รวมแล้ว), Devil’s Sight มองผ่านความมืดธรรมดาและเวทได้ 120 ฟุต, Mask of Many Faces ร่าย Disguise Self ได้ไม่จำกัด Dark One’s Blessing: ทำศัตรูเหลือ 0 HP ได้ HP ชั่วคราว 9 หน่วย ซึ่งไม่สะสมกับของเดิม ต้านทานไฟ มองในความมืด 60 ฟุต Pact of the Chain ให้ร่าย Find Familiar แบบพิธีกรรม มีนกฮูกชื่อ Cinder อยู่แล้ว: AC 11, HP 1, เดิน 5/บิน 60 ฟุต, STR 3 DEX 13 CON 8 INT 2 WIS 12 CHA 7, Perception +3, Stealth +3, มองในความมืด 120 ฟุต, Passive Perception 13 ได้เปรียบ Perception ที่ใช้ตาหรือหู Flyby ป้องกัน Opportunity Attack เมื่อบินออกจากระยะ เข้าใจภาษาคุณแต่พูดไม่ได้ มี Initiative ของตัวเองและใช้ Help ได้ ใช้แอ็กชันรับภาพและเสียงผ่านมันจนถึงเทิร์นถัดไปเมื่ออยู่ใน 100 ฟุต ระหว่างนั้นใช้ประสาทสัมผัสตัวเองไม่ได้ ปกติมันโจมตีไม่ได้ คุณยอมสละการโจมตีหนึ่งครั้งจาก Attack เพื่อให้มันใช้รีแอ็กชันโจมตีกรงเล็บได้ (+3, slashing 1) อัญเชิญใหม่ใช้วัตถุดิบ 10 gp'),
    equipment: t('Studded leather, dagger, arcane focus, diplomat’s pack, dice set, forgery kit (corporate IDs), contract fragment. Tools: dice set, forgery kit. Languages: Common, Infernal. Corporate Red Tape identifies the relevant department and deciphers routine forms; it does not guarantee cooperation. Old contract: 10% pledged, 20 SoulCoin available, one nonviolent courier delivery/month; release for 100 SoulCoin or two more completed monthly deliveries. Spells remain available even when refusing a mission.', 'Studded leather, Dagger, โฟกัส, Diplomat’s pack, ชุดลูกเต๋า, Forgery kit สำหรับบัตรองค์กร และเศษสัญญา เครื่องมือ: ชุดลูกเต๋า, Forgery kit ภาษา: Common, Infernal Corporate Red Tape ช่วยรู้แผนกและอ่านเอกสารทั่วไป แต่ไม่รับประกันความร่วมมือ สัญญาเก่าผูกวิญญาณ 10% มี SoulCoin 20 เหรียญ ต้องส่งของที่ไม่ใช้ความรุนแรงเดือนละครั้ง ปลดได้ด้วย 100 SoulCoin หรือส่งของครบอีกสองเดือน แม้ปฏิเสธภารกิจก็ยังใช้เวทได้'),
    story: t('Ideal: self-ownership. Flaw: makes promises too easily. Kael treats your former coworkers without asking names. Nyx kept your warning confidential; Ash never reported your brand. Your former employer still sends courier orders, but no one controls your loyalties.', 'อุดมคติคือเป็นเจ้าของชีวิตตัวเอง จุดอ่อนคือรับปากง่าย Kael รักษาอดีตเพื่อนร่วมงานโดยไม่ถามชื่อ Nyx เก็บคำเตือนของคุณเป็นความลับ Ash ไม่เคยรายงานตราสัญญาของคุณ นายจ้างเก่ายังส่งคำสั่งมา แต่ไม่มีใครกำหนดความภักดีของคุณ'),
    turn: t('Make two separate Eldritch Blast attacks. Hex uses a bonus action and concentration; Counterspell uses a reaction and a pact slot. Recover both pact slots on a short rest. Keep Cinder away from area damage.', 'ทอย Eldritch Blast แยกสองครั้ง Hex ใช้โบนัสแอ็กชันและสมาธิ Counterspell ใช้รีแอ็กชันกับช่อง Pact พักสั้นฟื้นช่อง Pact ทั้งสองช่อง อย่าให้ Cinder อยู่ในพื้นที่โจมตีวงกว้าง'),
  },
  {
    id: 'ash', name: 'Brother Ash', ancestry: t('Hill dwarf', 'คนแคระเนินเขา'), klass: 'Cleric', subclass: 'Life Domain',
    role: t('Ripperdoc · custom clinic attendant background', 'Ripperdoc · ภูมิหลังผู้ช่วยคลินิก'),
    level: 5, hitDie: 8, hp: 48, hpPerLevel: 1, ac: 18, speed: 25, scores: [14, 10, 16, 10, 18, 12], asi: 'WIS',
    saves: ['WIS', 'CHA'], skills: { Medicine: 1, Insight: 1, Religion: 1, Persuasion: 1 },
    attacks: [{ name: 'Warhammer', ability: 'STR', dice: '1d8', type: 'bludgeoning', range: '5 ft' }, { name: 'Sacred Flame', ability: 'WIS', dice: '2d8', type: 'radiant', spell: true, save: 'DEX', range: '60 ft' }],
    casting: { ability: 'WIS', slots: [4, 3, 2], cantrips: ['Sacred Flame', 'Guidance', 'Light', 'Spare the Dying'], prepared: ['Healing Word', 'Sanctuary', 'Detect Magic', 'Command', 'Aid', 'Prayer of Healing', 'Silence', 'Dispel Magic', 'Spirit Guardians'], domain: ['Bless', 'Cure Wounds', 'Lesser Restoration', 'Spiritual Weapon', 'Beacon of Hope', 'Revivify'] },
    features: t('Disciple of Life: healing spells of level 1+ restore an additional 2 + slot level HP per target. Channel Divinity once/short or long rest: Turn Undead (WIS DC 15; destroyed if CR 1/2 or lower on failure) or Preserve Life (action; distribute 25 HP among creatures within 30 ft, none above half maximum; no undead/constructs). Ritual casting of prepared ritual spells. Dwarven Toughness adds 1 HP/level (included). Darkvision 60 ft; poison resistance and advantage on saves against poison. Stonecunning: double proficiency on History checks about stonework. Heavy armor does not reduce your speed. Dwarf weapon training includes warhammer.', 'Disciple of Life: เวทรักษาระดับ 1 ขึ้นไปฟื้นเพิ่ม 2 + ระดับช่องเวทต่อเป้าหมาย Channel Divinity หนึ่งครั้งต่อการพักสั้นหรือยาว เลือก Turn Undead (WIS DC 15 ถ้า CR ไม่เกิน 1/2 และเซฟไม่ผ่านจะถูกทำลาย) หรือ Preserve Life ใช้แอ็กชันแบ่ง 25 HP ให้ผู้ที่อยู่ใน 30 ฟุต แต่ไม่เกินครึ่ง HP สูงสุดของแต่ละคน ไม่ใช้กับอันเดดหรือสิ่งสร้าง ร่ายพิธีกรรมจากเวทที่เตรียมได้ Dwarven Toughness เพิ่ม 1 HP ต่อเลเวล (รวมแล้ว) มองในความมืด 60 ฟุต ต้านทานพิษและได้เปรียบเซฟต้านพิษ Stonecunning เพิ่มความชำนาญสองเท่าเมื่อเช็ก History เรื่องงานหิน เกราะหนักไม่ลดความเร็ว ชำนาญ Warhammer จากเผ่าพันธุ์'),
    equipment: t('Chain mail, shield bearing holy symbol, warhammer, healer’s kit (10 uses), priest’s pack, herbalism kit, mason’s tools. Tools: herbalism kit, mason’s tools. Languages: Common, Dwarvish, Celestial (background). Clinic background: independent clinics offer a place to rest in return for a shift; supplies still cost money. Revivify consumes 300 gp diamonds, not provided; it is unavailable until these are obtained. Lay down your hammer to keep a hand free for somatic-only spells.', 'Chain mail, โล่ติดสัญลักษณ์ศักดิ์สิทธิ์, Warhammer, Healer’s kit (10 ครั้ง), Priest’s pack, Herbalism kit และเครื่องมือช่างหิน เครื่องมือ: Herbalism kit, เครื่องมือช่างหิน ภาษา: Common, Dwarvish, Celestial (จากภูมิหลัง) คลินิกอิสระให้พักแลกกับช่วยงานหนึ่งกะ แต่เวชภัณฑ์ยังมีราคา Revivify ใช้เพชร 300 gp จนหมด ซึ่งยังไม่ได้รับ จึงยังร่ายไม่ได้ วางค้อนเพื่อให้มีมือว่างสำหรับเวทที่ต้องทำท่าทางอย่างเดียว'),
    story: t('Ideal: no one dies for lack of coin. Flaw: cannot refuse a patient. Kael is your mentor, not your employer. Sable delivered medicine when her corporation forbade it. Kestrel finds the patients who disappear from the registers. Your former temple wants you to stop treating rebels.', 'อุดมคติคือไม่มีใครควรตายเพราะไร้เงิน จุดอ่อนคือปฏิเสธผู้ป่วยไม่ได้ Kael เป็นครู ไม่ใช่นายจ้าง Sable เคยส่งยาแม้องค์กรห้าม Kestrel ตามหาผู้ป่วยที่หายจากทะเบียน วิหารเก่าต้องการให้คุณเลิกรักษากบฏ'),
    turn: t('Bless helps allies but needs concentration. Healing Word can rescue a fallen ally as a bonus action; if you cast it, your other spell that turn must be a one-action cantrip. Preserve Life is an action, not a spell.', 'Bless ช่วยเพื่อนแต่ต้องใช้สมาธิ Healing Word ช่วยเพื่อนที่ล้มด้วยโบนัสแอ็กชัน ถ้าร่ายแล้ว เวทอื่นในเทิร์นนั้นต้องเป็น Cantrip ที่ใช้หนึ่งแอ็กชัน Preserve Life ใช้แอ็กชันแต่ไม่ใช่เวท'),
  },
  {
    id: 'kestrel', name: 'Kestrel', ancestry: t('Half-orc', 'ครึ่งออร์ค'), klass: 'Rogue', subclass: 'Thief',
    role: t('Fixer · custom neighborhood broker background', 'Fixer · ภูมิหลังนายหน้าชุมชน'),
    level: 5, hitDie: 8, hp: 38, ac: 16, speed: 30, scores: [10, 18, 14, 12, 10, 14], asi: 'DEX',
    saves: ['DEX', 'INT'], skills: { Acrobatics: 1, Deception: 2, Insight: 1, Investigation: 1, 'Sleight of Hand': 1, Stealth: 2, Intimidation: 1 },
    attacks: [{ name: 'Rapier', ability: 'DEX', dice: '1d8', type: 'piercing', range: '5 ft' }, { name: 'Shortbow', ability: 'DEX', dice: '1d6', type: 'piercing', range: '80/320 ft' }],
    features: t('Sneak Attack adds 3d6 once per turn with a finesse/ranged weapon when you have advantage, or an enemy of your target is within 5 ft of it and not incapacitated; you must not have disadvantage. Expertise: Stealth and Deception (included). Cunning Action: bonus-action Dash, Disengage or Hide. Fast Hands also allows bonus-action Sleight of Hand, thieves’ tools to disarm/open locks, or Use an Object (not magic-item activation). Second-Story Work: climbing costs no extra movement; running jump distance +4 ft. Uncanny Dodge: reaction halves one hit from an attacker you can see. Darkvision 60 ft. Relentless Endurance: once/long rest, drop to 1 HP instead of 0 unless killed outright. Savage Attacks adds one extra weapon die on a melee critical hit. Thieves’ Cant.', 'Sneak Attack เพิ่ม 3d6 เทิร์นละครั้งด้วยอาวุธ Finesse หรือระยะไกล เมื่อได้เปรียบ หรือมีศัตรูของเป้าหมายอยู่ใน 5 ฟุตและยังทำอะไรได้ โดยคุณต้องไม่เสียเปรียบ Expertise: Stealth, Deception (รวมแล้ว) Cunning Action ใช้โบนัสแอ็กชัน Dash, Disengage หรือ Hide Fast Hands เพิ่ม Sleight of Hand ใช้ Thieves’ Tools ปลดกับดักหรือไขล็อก และ Use an Object (ไม่รวมเปิดใช้ไอเทมเวท) Second-Story Work ปีนไม่เสียระยะเพิ่ม และกระโดดแบบวิ่งเพิ่ม 4 ฟุต Uncanny Dodge ใช้รีแอ็กชันลดความเสียหายครึ่งหนึ่งจากการโจมตีที่มองเห็น มองในความมืด 60 ฟุต Relentless Endurance: หนึ่งครั้งต่อพักยาว เหลือ 1 HP แทน 0 หากไม่ตายทันที Savage Attacks เพิ่มลูกเต๋าอาวุธหนึ่งลูกเมื่อคริติคอลระยะประชิด รู้ Thieves’ Cant'),
    equipment: t('Studded leather, rapier, shortbow, 20 arrows, thieves’ tools, forgery kit, dice set, burglar’s pack, gold comm-stone. Tools: thieves’ tools, forgery kit, dice set. Languages: Common, Orc. Background: a market contact introduces buyers and sellers; prices and trust must still be negotiated.', 'Studded leather, Rapier, Shortbow, ลูกธนู 20 ดอก, Thieves’ Tools, Forgery kit, ชุดลูกเต๋า, Burglar’s pack และ Gold comm-stone เครื่องมือ: Thieves’ Tools, Forgery kit, ชุดลูกเต๋า ภาษา: Common, Orc ภูมิหลังให้ผู้ติดต่อแนะนำคนซื้อขาย แต่ยังต้องต่อรองราคาและความเชื่อใจ'),
    story: t('Ideal: mutual aid. Flaw: cannot resist a secret. You owe the kitchen a month of washing up. Ash kept your friends alive; Ilyra always pays her porters. Echo-9 wants access to your contact list. Decide which names you will never sell.', 'อุดมคติคือช่วยเหลือกัน จุดอ่อนคืออดรู้ความลับไม่ได้ คุณค้างงานล้างจานโรงครัวหนึ่งเดือน Ash ช่วยเพื่อนคุณให้รอด Ilyra จ่ายค่าลูกหาบเสมอ Echo-9 อยากได้รายชื่อผู้ติดต่อของคุณ กำหนดชื่อที่คุณจะไม่มีวันขาย'),
    turn: t('Attack a foe beside your ally for Sneak Attack, then Disengage with your bonus action. Keep your reaction for Uncanny Dodge. You make one attack per Attack action.', 'โจมตีศัตรูที่ยืนข้างเพื่อนเพื่อใช้ Sneak Attack แล้วใช้โบนัสแอ็กชัน Disengage เก็บรีแอ็กชันไว้ใช้ Uncanny Dodge คุณโจมตีครั้งเดียวต่อ Attack'),
  },
  {
    id: 'ilyra', name: 'Ilyra Moss', ancestry: t('Wood elf', 'เอลฟ์ป่า'), klass: 'Ranger', subclass: 'Hunter',
    role: t('Bleed scavenger · Bleed Scavenger background', 'นักเก็บกู้ Bleed · ภูมิหลังนักเก็บกู้'),
    level: 5, hitDie: 10, hp: 44, ac: 16, speed: 35, scores: [10, 18, 14, 10, 14, 10], asi: 'DEX',
    saves: ['STR', 'DEX'], skills: { Nature: 1, Perception: 1, Stealth: 1, Survival: 1, Investigation: 1, Insight: 1 },
    attacks: [{ name: 'Longbow', ability: 'DEX', dice: '1d8', type: 'piercing', accuracy: 2, range: '150/600 ft' }, { name: 'Shortsword', ability: 'DEX', dice: '1d6', type: 'piercing', range: '5 ft' }],
    casting: { ability: 'WIS', slots: [4, 2], cantrips: [], known: ['Hunter’s Mark', 'Cure Wounds', 'Goodberry', 'Pass without Trace'] },
    features: t('Archery: +2 on ranged weapon attack rolls (included). Extra Attack: two attacks per Attack action. Colossus Slayer: once per turn on a weapon hit, +1d8 if the target was already below maximum HP. Favored Enemy: aberrations; advantage on Survival to track and Intelligence to recall facts about them. Natural Explorer: swamp (the Bleed marshes); double proficiency on relevant Intelligence or Wisdom checks while tracking aberrations or recalling facts about them; for travel of 1 hour+ there, ignore difficult terrain for group travel, cannot become lost except magically, remain alert while doing other travel work, find twice as much forage, and learn number/size/age of tracks; travel stealthily at normal pace when alone. Primeval Awareness (level 3): as an action, expend one ranger spell slot to sense whether aberrations, celestials, dragons, elementals, fey, fiends, or undead are within 5 miles (1 mile outside favored terrain) for 1 minute per spell-slot level; this reveals neither location nor number. Darkvision 60 ft; charm-save advantage; magical sleep immunity; 4-hour trance (table’s 2014 rest ruling). Mask of the Wild allows hiding when lightly obscured by natural foliage, rain, snow or mist.', 'Archery เพิ่มผลโจมตีอาวุธระยะไกล +2 (รวมแล้ว) Extra Attack โจมตีสองครั้งต่อ Attack Colossus Slayer เพิ่ม 1d8 เทิร์นละครั้งเมื่ออาวุธโดนศัตรูที่มี HP ต่ำกว่าค่าสูงสุดอยู่ก่อน Favored Enemy: aberrations ได้เปรียบ Survival ตามรอยและ Intelligence นึกข้อมูล Natural Explorer: swamp หรือบึงใน Bleed เพิ่ม proficiency เป็นสองเท่าสำหรับการตรวจ Intelligence หรือ Wisdom ที่เกี่ยวข้องขณะตามรอย aberrations หรือนึกข้อมูลเกี่ยวกับพวกมัน เมื่อเดินทางอย่างน้อย 1 ชั่วโมง กลุ่มไม่ช้าลงจากพื้นลำบาก ไม่หลงทางเว้นแต่ด้วยเวท คุณยังระวังภัยขณะทำงานอื่น หาอาหารได้สองเท่า และรู้จำนวน ขนาด อายุรอยเท้า ถ้าเดินคนเดียวซ่อนตัวด้วยความเร็วปกติได้ Primeval Awareness (เลเวล 3): ใช้ action และ spell slot ของ ranger หนึ่งช่องเพื่อตรวจว่ามี aberrations, celestials, dragons, elementals, fey, fiends หรือ undead ในระยะ 5 ไมล์ หรือ 1 ไมล์นอก favored terrain เป็นเวลา 1 นาทีต่อเลเวลช่องเวท แต่ไม่รู้ตำแหน่งหรือจำนวน มองในความมืด 60 ฟุต ได้เปรียบเซฟต้าน charm ไม่หลับด้วยเวท เข้าภวังค์ 4 ชั่วโมงตามข้อตกลงการพักปี 2014 ของโต๊ะ Mask of the Wild ให้ซ่อนเมื่อพืช ฝน หิมะ หรือหมอกธรรมชาติบังบางส่วน'),
    equipment: t('Studded leather, longbow, 20 arrows, two shortswords, component pouch, explorer’s pack, navigator’s tools, tinker’s tools, storm compass. Tools: navigator’s tools, tinker’s tools. Languages: Common, Elvish, Deep Speech (favored enemy). Ruins Navigator finds known routes and fences; magical hazards still require checks. Two-weapon bonus attack uses the second shortsword without +DEX damage.', 'Studded leather, Longbow, ลูกธนู 20 ดอก, Shortsword สองเล่ม, Component pouch, Explorer’s pack, Navigator’s Tools, Tinker’s Tools และเข็มทิศพายุ เครื่องมือ: Navigator’s Tools, Tinker’s Tools ภาษา: Common, Elvish, Deep Speech (จาก Favored Enemy) Ruins Navigator ช่วยหาเส้นทางที่รู้จักและคนรับซื้อ แต่ภัยเวทยังต้องเช็ก โบนัสโจมตีด้วยดาบมือรองไม่บวก DEX ในความเสียหาย'),
    story: t('Ideal: endure together. Flaw: sleeps with one eye open. Mara shares your salvage routes; Kestrel keeps smugglers from exploiting your porters. Jun once carried you out of a storm. The Syndicate claims your last find belongs to it.', 'อุดมคติคือรอดไปด้วยกัน จุดอ่อนคือระแวงแม้ยามหลับ Mara ใช้เส้นทางเก็บกู้ร่วมกับคุณ Kestrel กันพ่อค้าจากการเอาเปรียบลูกหาบ Jun เคยแบกคุณออกจากพายุ Syndicate อ้างสิทธิในของที่คุณเพิ่งพบ'),
    turn: t('Use two longbow attacks and add Colossus Slayer once when eligible. Hunter’s Mark needs concentration and a bonus action; it cannot run alongside Pass without Trace.', 'ยิง Longbow สองครั้ง เพิ่ม Colossus Slayer ครั้งเดียวเมื่อเข้าเงื่อนไข Hunter’s Mark ใช้สมาธิและโบนัสแอ็กชัน จึงใช้ร่วมกับ Pass without Trace ไม่ได้'),
  },
  {
    id: 'jun', name: 'Jun Vale', ancestry: t('Human', 'มนุษย์'), klass: 'Monk', subclass: 'Way of the Open Hand',
    role: t('Faraday Order · custom signal keeper background', 'Faraday Order · ภูมิหลังผู้เฝ้าสัญญาณ'),
    level: 5, hitDie: 8, hp: 38, ac: 16, speed: 40, scores: [10, 18, 14, 10, 14, 12], asi: 'DEX',
    saves: ['STR', 'DEX'], skills: { Acrobatics: 1, Athletics: 1, Insight: 1, Stealth: 1 },
    attacks: [{ name: 'Unarmed strike', ability: 'DEX', dice: '1d6', type: 'bludgeoning', range: '5 ft' }, { name: 'Quarterstaff (two hands)', ability: 'DEX', dice: '1d8', type: 'bludgeoning', range: '5 ft' }, { name: 'Dart', ability: 'DEX', dice: '1d4', type: 'piercing', range: '20/60 ft' }],
    features: t('Ki 5, recovered after a short/long rest with 30 minutes meditation; Ki save DC 13. No armor/shield: Unarmored Defense (AC 10+DEX+WIS), speed +10 ft, Martial Arts (d6; bonus-action unarmed strike after Attack with unarmed/monk weapon). Extra Attack: two attacks. Flurry of Blows: immediately after Attack, spend 1 ki for two bonus-action unarmed strikes instead of one. Each Flurry hit can deny reactions until your next turn, knock prone on failed DEX save, or push 15 ft on failed STR save. Patient Defense: 1 ki, bonus-action Dodge. Step of the Wind: 1 ki, bonus-action Dash/Disengage and double jump distance this turn. Stunning Strike: 1 ki on a melee weapon hit; failed CON save stuns until end of your next turn (unarmed strikes qualify). Deflect Missiles: reaction reduces ranged weapon damage by 1d10+9; if reduced to zero and a hand is free, catch it; spend 1 ki to throw it in the same reaction (20/60 ft, +7, 1d6+4). Slow Fall: reaction reduces falling damage by 25. Human score increases included.', 'Ki 5 ฟื้นเมื่อพักสั้นหรือยาวและทำสมาธิ 30 นาที Ki save DC 13 เมื่อไม่สวมเกราะหรือโล่ Unarmored Defense ให้ AC 10+DEX+WIS ความเร็วเพิ่ม 10 ฟุต Martial Arts ใช้ d6 และโบนัสโจมตีมือเปล่าหลัง Attack ด้วยมือเปล่าหรืออาวุธ Monk Extra Attack โจมตีสองครั้ง Flurry of Blows ใช้ 1 ki ทันทีหลัง Attack เพื่อโจมตีมือเปล่าสองครั้งด้วยโบนัสแอ็กชันแทนหนึ่งครั้ง แต่ละหมัดที่โดนเลือกปิดรีแอ็กชันจนถึงเทิร์นถัดไปของคุณ ทำล้มเมื่อ DEX เซฟพลาด หรือผลัก 15 ฟุตเมื่อ STR เซฟพลาด Patient Defense: 1 ki ใช้โบนัสแอ็กชัน Dodge Step of the Wind: 1 ki ใช้โบนัสแอ็กชัน Dash หรือ Disengage และกระโดดไกลสองเท่าในเทิร์นนั้น Stunning Strike: 1 ki เมื่อโจมตีอาวุธประชิดโดน รวมมือเปล่า หาก CON เซฟพลาดจะมึนงงจนจบเทิร์นถัดไปของคุณ Deflect Missiles ใช้รีแอ็กชันลดความเสียหายอาวุธระยะไกล 1d10+9 หากเหลือศูนย์และมีมือว่างจะรับไว้ได้ ใช้ 1 ki ขว้างกลับในรีแอ็กชันเดียวกัน (20/60 ฟุต, +7, 1d6+4) Slow Fall ใช้รีแอ็กชันลดความเสียหายตกจากที่สูง 25 รวมค่าจากมนุษย์แล้ว'),
    equipment: t('Quarterstaff, 10 darts, explorer’s pack, Faraday prayer beads, calligrapher’s supplies, flute. Tools: calligrapher’s supplies (class), flute (background). Languages: Common, Celestial (human), Primordial (background). Background: the Order offers a quiet place to meditate and introductions to signal keepers; scanners are not automatically defeated by your class.', 'Quarterstaff, Dart 10 ดอก, Explorer’s pack, ลูกประคำ Faraday, อุปกรณ์เขียนอักษร และขลุ่ย เครื่องมือ: อุปกรณ์เขียนอักษรจากคลาส ขลุ่ยจากภูมิหลัง ภาษา: Common, Celestial จากมนุษย์, Primordial จากภูมิหลัง ภูมิหลังให้ที่สงบทำสมาธิและแนะนำผู้เฝ้าสัญญาณ แต่คลาสไม่ทำให้ผ่านเครื่องตรวจได้อัตโนมัติ'),
    story: t('Ideal: discipline in service of others. Flaw: mistakes restraint for wisdom. You teach breathing exercises at the clinic. Ilyra trusted you in a storm; Aster always brings medicine before collecting pay. Your Order wants an unstable signal silenced, but patients rely on its power.', 'อุดมคติคือฝึกตนเพื่อช่วยผู้อื่น จุดอ่อนคือคิดว่าความอดกลั้นคือปัญญาเสมอ คุณสอนฝึกลมหายใจที่คลินิก Ilyra เคยฝากชีวิตกลางพายุ Aster ส่งยาก่อนเก็บเงินทุกครั้ง สำนักต้องการปิดสัญญาณที่ไม่เสถียร แต่ผู้ป่วยยังพึ่งพาพลังจากมัน'),
    turn: t('Attack twice with the staff, then make one unarmed bonus attack or spend 1 ki for two. Stunning Strike and Flurry can spend several ki in a turn; track the pool. Unarmed attacks are not yet magical at level 5.', 'โจมตีกระบองสองครั้ง แล้วโบนัสโจมตีมือเปล่าหนึ่งครั้ง หรือจ่าย 1 ki เพื่อสองครั้ง Stunning Strike และ Flurry ใช้ ki หลายแต้มในเทิร์นเดียวได้ จดแต้มที่เหลือ การโจมตีมือเปล่ายังไม่เป็นเวทที่เลเวล 5'),
  },
]

export const abilities = ['STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA']
export const skillAbilities = { Acrobatics: 'DEX', Arcana: 'INT', Athletics: 'STR', Deception: 'CHA', History: 'INT', Insight: 'WIS', Intimidation: 'CHA', Investigation: 'INT', Medicine: 'WIS', Nature: 'INT', Perception: 'WIS', Persuasion: 'CHA', Religion: 'INT', 'Sleight of Hand': 'DEX', Stealth: 'DEX', Survival: 'WIS' }
export const abilityMod = (character, ability) => modifier(character.scores[abilities.indexOf(ability)])
export const proficiency = character => 2 + Math.floor((character.level - 1) / 4)
export const skillBonus = (character, skill) => abilityMod(character, skillAbilities[skill]) + (character.skills[skill] || 0) * proficiency(character)
export const attackBonus = (character, attack) => abilityMod(character, attack.ability) + proficiency(character) + (attack.accuracy || 0)
export const spellDC = character => 8 + proficiency(character) + abilityMod(character, character.casting.ability)
